### ISSUE TITLE
make: *** [src/VarQuin/v_split.o] Error 1

### ISSUE THREAD

**Issue by danielnavarrogomez** [student-t/Anaquin#3]
Hi,

Having troubles to compile Anaquin.
installed dependencies:
- Boost/1.57.0
- klib
- vcflib
- HTSlib/1.1
- eigen/3.3.4
- GCC/5.2.0

I attach the log of the compilation.

[make_log.txt](https://github.com/student-t/Anaquin/files/1306961/make_log.txt)

**Comment by student-t** [comment]
Thanks for reporting.

It looks like the C++ function `extern FileName VCFRef();` is not found in your compilation. Your compiler should have found it because the definition is in main.cpp.

I just tried to clean up everything and recompiled myself, it worked for me. Let's try this:

1. Get the latest source code and compile again
2. If that doesn't work, tell me the version number for your C++ compiler
3. I can always modify the source code if we can't make it compile with your C++ compiler.

**Comment by danielnavarrogomez** [comment]
Hi, thanks for your answer.

I tried to start from fresh (new clone) and I tried gcc 5.2.0 with same results:
undefined reference to VCFRef() (attached complete log)
[make_log.txt](https://github.com/student-t/Anaquin/files/1310731/make_log.txt)

Could the problem be related to any dependency? Just guessing.

**Comment by student-t** [comment]
We're using different C++ compiler. The code definitely works for me, but not your compiler. Give me a day. I'll try to install the gcc 5.2.0. Otherwise, I'll just change the source code.

**Comment by danielnavarrogomez** [comment]
Will be easy for me to change compilers, which version did you use?

**Comment by danielnavarrogomez** [comment]
I just tried gcc 4.7.2 and I get a different error:
[make_log_4.7.2.txt](https://github.com/student-t/Anaquin/files/1310789/make_log_4.7.2.txt)

**Comment by student-t** [comment]
I'm using g++ 4.8.4.

tedwon@mercer:~/Sources/QA$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by student-t** [comment]
One of the files might need to add `#include <stdexcept>`, which I just did and committed to the source code.

I don't understand why it would compile on me (I tested on three different Linux machines), but not yours.

As mentioned, if nothing works. I'll just modify the source code for the `VCFRef()` function.

**Comment by danielnavarrogomez** [comment]
Hi,

It is compiling just fine using g++ 4.8.4, not with 4.7.2 neither 5.2.0.

Thanks and I close the issue.

**Comment by student-t** [comment]
Furthermore, we're about to push a significant update for Anaquin and sequins. The current development version is a bit different to the user manual. If you encounter problems, please tell me. 

Finally, Anaquin is a beta software so please give me feedback. Let's make it to production ready!
