### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by russianconcussion** [student-t/Anaquin#5]
Hi, I cloned the Anaquin git repository and I am trying to compile. I've installed eigen, boost, htclib libraries and explicitly included them in the Makefile. When I run make, it complains about a variable 'isnan' that "isn't declared in this scope". Not sure how to fix that! Any help greatly appreciated! Thanks for the awesome software.

[make_error.txt](https://github.com/student-t/Anaquin/files/2002785/make_error.txt)

**Comment by student-t** [comment]
I think r_sample.cpp needs to have include the header file for the isnan() function. For some reason, my compiler was able to compile without the header file. Your compiler might need it.

I will give check the code better later today.

**Comment by student-t** [comment]
https://github.com/student-t/Anaquin/commit/75189e58de3a699aa5f87d31b80e945dd364bf54

**Comment by russianconcussion** [comment]
Hi, @student-t, thanks for the fix. I found more of the same error cropping up in other src files. Then I found this post on stackoverflow, which seems to be relevant:
https://stackoverflow.com/questions/18128899/is-isnan-in-the-std-namespace-more-in-general-when-is-std-necessary-optio

So, I just replaced ALL instances of "isnan" with "std::isnan" with this script run from the Anaquin directory as well as instances of "isinf" with "std::isinf":
`find -iname "*.[hc]pp" -print0 | xargs -0 sed -i 's/isnan/std::isnan/g;s/std::std::isnan/std::isnan/g;s/isinf/std::isinf/g;s/std::std::isinf/std::isinf/g'`
and it compiled without error and the binary seems to run fine.

My compiler is gcc version 5.4.0 20160609

**Comment by student-t** [comment]
Thanks. I was confused about those C/C++ little details. Apology. BTW: we're going to make a new gigantic release soon, for new sequins not covered here yet.

**Comment by russianconcussion** [comment]
Ah, brilliant! Thanks for the info, @student-t! Will there be more detail about metasequins? I am trying to use your software with metasequins and I noticed that there's no mention of them in the documentation. I'm just following the RNASeq instructions as it seems like it should be analogous to the metagenomics workflow.

**Comment by student-t** [comment]
Please write to my team leader (Timothy Mercer <t.mercer@garvan.org.au>). He will be able to answer your sequin questions about metagenomics.
