### ISSUE TITLE
./anaquin: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by russianconcussion** [student-t/Anaquin#6]
Hello,

I've tried to compile the newest version of Anaquin with the newest stable version of htslib (1.9), but to no avail because of the libhts.so.2 file in the hts library. It's just a symlink to the libhts.so file, so not sure what the big deal is. I've made sure to set the HTSLIB variable in the Makefile to the new installation dir of htslib-1.9. I've tried substituting or adding the libhts.so and libhts.so.2 files you offer to my LD_LIBRARY_PATH, then recompiling. That also failed. I've tried all sorts of things, but nothing's worked this afternoon. Am I using an incompatible new version of htslib?

**Comment by russianconcussion** [comment]
Aiyiyi. It was a simple spelling error when exporting the htslib-1.9 library path in the LD_LIBRARY_PATH.
This solved my problem, and I will put it in my .bashrc file:
export LD_LIBRARY_PATH=/home/nmb/bioinformatics/htslib-1.9

**Comment by student-t** [comment]
: - )
