### ISSUE TITLE
Trouble with anaquin RnaFoldChange

### ISSUE THREAD

**Issue by russianconcussion** [student-t/Anaquin#7]
Hi,

I am trying to use anaquin for quantitative metagenomics. I've run my data through DESeq2 just fine, and reformatted the Metaquins text file to fit the RNA isoforms mix file format for the -rmix argument. However, when I issue the command below, I get a summary file that tells me I only have 1 sequin in my rmix file (I should have 86 sequins)!
`anaquin RnaFoldChange -o IG_01 -rmix ../Metasequins_isoform_mix.txt -mix A -usequin DESeq2.csv` 

Here is the summary file:
[RnaFoldChange_summary.stats.txt](https://github.com/student-t/Anaquin/files/2550101/RnaFoldChange_summary.stats.txt)

And the sequins file generated by anaquin:
[RnaFoldChange_sequins.tsv.txt](https://github.com/student-t/Anaquin/files/2550985/RnaFoldChange_sequins.tsv.txt)

Here is the rmix file that I formatted for the metaquins (from Metasequins details text file on www.sequin.xyz):
[Metasequins_isoform_mix.txt](https://github.com/student-t/Anaquin/files/2550104/Metasequins_isoform_mix.txt)

What am I doing wrong with the rmix file?

**Comment by student-t** [comment]
Thanks. I'm going to take a look very soon. Will get back to you later today.

**Comment by russianconcussion** [comment]
Hi, thanks very much!

**Comment by student-t** [comment]
Do you have a copy of DESeq2.csv that you can share? If it's too big, Dropox link is welcome.

**Comment by russianconcussion** [comment]
Hi Ted,
Thanks, I've emailed it to you.

**Comment by student-t** [comment]
Thanks.

The problem was the incorrect tool. "RnaFoldChange" was an RNA tool, and expected sequin genes/isoforms. However, the metagenomics reference didn't have any isoform. Thus, the tool wasn't able to work out anything meaningful.

RnaFoldChange will not work for metagenomics. Do you want to use R for your task?

**Comment by russianconcussion** [comment]
Hi Ted, thanks. I understood it to be a tool that could be used to measure fold changes of anything (isoform, gene, or contig) between more than one sample. I can cook up my own solution in R, though. Thanks!
